package databaseconnection;
public class AdminPage extends javax.swing.JFrame {

    public AdminPage() {
        initComponents();
        setLocationRelativeTo(null); // Center the window
        UserManagementButton.addActionListener(e -> {
        new UserManagement().setVisible(true);
        dispose(); // Close Admin Page
        });

        InventoryManagementButton.addActionListener(e -> {
            new InventoryMangement().setVisible(true);
            dispose();
        });

        TransactionMButton.addActionListener(e -> {
            

        });

        ViewSuppliersButton.addActionListener(e -> {
            new ViewSuppliers().setVisible(true);
            dispose();
        });

        ViewHospitalsButton.addActionListener(e -> {
            new ViewHospitals().setVisible(true);
            dispose();
        });

        LogoutButton.addActionListener(e -> {
            new LoginInterface().setVisible(true); // Go back to login
            dispose();
        });
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        UserManagementButton = new javax.swing.JButton();
        InventoryManagementButton = new javax.swing.JButton();
        TransactionMButton = new javax.swing.JButton();
        ViewSuppliersButton = new javax.swing.JButton();
        ViewHospitalsButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        BackgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Admin Page");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 18, -1, -1));

        UserManagementButton.setText("User Management");
        UserManagementButton.setPreferredSize(new java.awt.Dimension(128, 28));
        UserManagementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserManagementButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UserManagementButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 50, 168, -1));

        InventoryManagementButton.setText("Inventory Management");
        InventoryManagementButton.setPreferredSize(new java.awt.Dimension(128, 28));
        InventoryManagementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventoryManagementButtonActionPerformed(evt);
            }
        });
        getContentPane().add(InventoryManagementButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 84, 168, -1));

        TransactionMButton.setText("Transaction Management");
        TransactionMButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransactionMButtonActionPerformed(evt);
            }
        });
        getContentPane().add(TransactionMButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 118, 168, -1));

        ViewSuppliersButton.setText("View Suppliers");
        getContentPane().add(ViewSuppliersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 147, 168, -1));

        ViewHospitalsButton.setText("View Hospitals");
        getContentPane().add(ViewHospitalsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 176, 168, -1));

        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 217, -1, -1));

        BackgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseconnection/systembackground.png"))); // NOI18N
        BackgroundLabel.setText("Background");
        getContentPane().add(BackgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserManagementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserManagementButtonActionPerformed
        // TODO add your handling code here:
        new UserManagement().setVisible(true);
        dispose();
    }//GEN-LAST:event_UserManagementButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        // TODO add your handling code here:
        new LoginInterface().setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void TransactionMButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransactionMButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TransactionMButtonActionPerformed

    private void InventoryManagementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventoryManagementButtonActionPerformed
        // TODO add your handling code here:
        new InventoryMangement().setVisible(true);
        dispose();
    }//GEN-LAST:event_InventoryManagementButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundLabel;
    private javax.swing.JButton InventoryManagementButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton TransactionMButton;
    private javax.swing.JButton UserManagementButton;
    private javax.swing.JButton ViewHospitalsButton;
    private javax.swing.JButton ViewSuppliersButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
