package databaseconnection;
import javax.swing.JOptionPane;

public class CreateUser extends javax.swing.JFrame {

    public CreateUser() {
        initComponents();
        setLocationRelativeTo(null); // Center the window
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateUserLabel = new javax.swing.JLabel();
        UserIDLAbel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        UserTypeLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        UserIDField = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        EmailField = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        UserManagementButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        CreateButton = new javax.swing.JButton();
        BackgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CreateUserLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CreateUserLabel.setText("Create User ");
        getContentPane().add(CreateUserLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 26, -1, -1));

        UserIDLAbel.setText("UserID          :");
        UserIDLAbel.setPreferredSize(new java.awt.Dimension(82, 28));
        getContentPane().add(UserIDLAbel, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 67, -1, -1));

        NameLabel.setText("Name           :");
        NameLabel.setPreferredSize(new java.awt.Dimension(82, 28));
        getContentPane().add(NameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 107, -1, -1));

        UserTypeLabel.setText("User Type     :");
        UserTypeLabel.setPreferredSize(new java.awt.Dimension(82, 28));
        getContentPane().add(UserTypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 147, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Staff" }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(82, 28));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 147, 100, -1));

        jLabel1.setText("Email            :");
        jLabel1.setPreferredSize(new java.awt.Dimension(82, 28));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 187, -1, -1));

        jLabel2.setText("Contact Number  :");
        jLabel2.setPreferredSize(new java.awt.Dimension(87, 28));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 221, 107, -1));

        UserIDField.setPreferredSize(new java.awt.Dimension(82, 28));
        getContentPane().add(UserIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 67, 100, -1));

        jTextField1.setPreferredSize(new java.awt.Dimension(82, 28));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 107, 100, -1));

        EmailField.setPreferredSize(new java.awt.Dimension(100, 28));
        getContentPane().add(EmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 187, 136, -1));

        jTextField2.setPreferredSize(new java.awt.Dimension(70, 28));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 221, 136, -1));

        UserManagementButton.setText("<User Management");
        UserManagementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserManagementButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UserManagementButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 26, -1, -1));

        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 26, -1, -1));

        CreateButton.setText("Create");
        CreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CreateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 267, -1, -1));

        BackgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseconnection/systembackground.png"))); // NOI18N
        BackgroundLabel.setText("Background");
        getContentPane().add(BackgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        // TODO add your handling code here:
        new LoginInterface().setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void UserManagementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserManagementButtonActionPerformed
        // TODO add your handling code here:
        new UserManagement().setVisible(true);
        dispose();
    }//GEN-LAST:event_UserManagementButtonActionPerformed

    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonActionPerformed
        // TODO add your handling code here:
        String userID = UserIDField.getText().trim();
        String name = jTextField1.getText().trim();
        String userType = jComboBox1.getSelectedItem().toString();
        String email = EmailField.getText().trim();
        String contactStr = jTextField2.getText().trim();

        if (userID.isEmpty() || name.isEmpty() || email.isEmpty() || contactStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields must be filled.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            int phoneNum = Integer.parseInt(contactStr);
            String password = "password";

            // Use UserDAO instead of raw SQL
            UserDAO.addUser(userID, name, email, String.valueOf(phoneNum), userType, password);
            JOptionPane.showMessageDialog(this, "User created and saved to DB!");
            UserIDField.setText("");
            jTextField1.setText("");
            EmailField.setText("");
            jTextField2.setText("");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid contact number.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CreateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundLabel;
    private javax.swing.JButton CreateButton;
    private javax.swing.JLabel CreateUserLabel;
    private javax.swing.JTextField EmailField;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField UserIDField;
    private javax.swing.JLabel UserIDLAbel;
    private javax.swing.JButton UserManagementButton;
    private javax.swing.JLabel UserTypeLabel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
