package databaseconnection;
import javax.swing.JOptionPane;
public class DisplayUserTable extends javax.swing.JFrame {
    
    public DisplayUserTable(User user) {
        initComponents();
        setLocationRelativeTo(null);//center the window
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        UserIDLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        UserTypeLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        ContactNumberLabel = new javax.swing.JLabel();
        AdminPageButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();
        UserIDField = new javax.swing.JTextField();
        BackgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Display User Table");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 31, -1, -1));

        UserIDLabel.setText("User ID        :");
        UserIDLabel.setPreferredSize(new java.awt.Dimension(182, 28));
        getContentPane().add(UserIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 69, 82, -1));

        NameLabel.setText("Name          :");
        NameLabel.setPreferredSize(new java.awt.Dimension(182, 28));
        getContentPane().add(NameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 110, -1, -1));

        UserTypeLabel.setText("UserType     :");
        UserTypeLabel.setToolTipText("");
        UserTypeLabel.setPreferredSize(new java.awt.Dimension(182, 28));
        getContentPane().add(UserTypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 150, -1, -1));

        EmailLabel.setText("Email           :");
        EmailLabel.setToolTipText("");
        EmailLabel.setPreferredSize(new java.awt.Dimension(182, 28));
        getContentPane().add(EmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 190, -1, -1));

        ContactNumberLabel.setText("ContactNumber :");
        ContactNumberLabel.setMaximumSize(new java.awt.Dimension(182, 28));
        ContactNumberLabel.setPreferredSize(new java.awt.Dimension(182, 28));
        getContentPane().add(ContactNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 224, 203, -1));

        AdminPageButton.setText("< Admin Page");
        AdminPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminPageButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AdminPageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 28, -1, -1));

        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 28, -1, -1));

        SearchButton.setText("Search");
        SearchButton.setPreferredSize(new java.awt.Dimension(82, 28));
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 70, -1, -1));

        UserIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserIDFieldActionPerformed(evt);
            }
        });
        getContentPane().add(UserIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 72, 117, -1));

        BackgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseconnection/systembackground.png"))); // NOI18N
        BackgroundLabel.setText("Background");
        getContentPane().add(BackgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        // TODO add your handling code here:
        new LoginInterface().setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void AdminPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminPageButtonActionPerformed
        // TODO add your handling code here:
        new AdminPage().setVisible(true);
        dispose();
    }//GEN-LAST:event_AdminPageButtonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        String userID = UserIDField.getText().trim();

        if (userID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a User ID.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        displayUserDetails(userID);
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void UserIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserIDFieldActionPerformed
        SearchButton.doClick(); // simulate button click
    }//GEN-LAST:event_UserIDFieldActionPerformed

    private void displayUserDetails(String userID) {
        User user = UserDAO.getUserByID(userID);

        if (user != null) {
            NameLabel.setText("Name: " + user.getName());
            UserTypeLabel.setText("User Type: " + user.getUserType());
            EmailLabel.setText("Email: " + user.getEmail());
            ContactNumberLabel.setText("Contact Number: " + user.getPhoneNum());
        } else {
            JOptionPane.showMessageDialog(this, "User not found.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
        
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayUserTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayUserTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayUserTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayUserTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new DisplayUserTable().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminPageButton;
    private javax.swing.JLabel BackgroundLabel;
    private javax.swing.JLabel ContactNumberLabel;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField UserIDField;
    private javax.swing.JLabel UserIDLabel;
    private javax.swing.JLabel UserTypeLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
