package databaseconnection;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
public class ForgetPassword extends javax.swing.JFrame {

    public ForgetPassword() {
        initComponents();
        setLocationRelativeTo(null); // Center the window
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ForgetPassLabel = new javax.swing.JLabel();
        UserIDLabel = new javax.swing.JLabel();
        NewPassLabel = new javax.swing.JLabel();
        UserIDField = new javax.swing.JTextField();
        NewPassfField = new javax.swing.JTextField();
        ResetButton = new javax.swing.JButton();
        LoginButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ForgetPassLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ForgetPassLabel.setText("Forget Password");
        getContentPane().add(ForgetPassLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 26, -1, -1));

        UserIDLabel.setText("User ID           :");
        UserIDLabel.setPreferredSize(new java.awt.Dimension(82, 28));
        getContentPane().add(UserIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 67, -1, -1));

        NewPassLabel.setText("New Password:");
        NewPassLabel.setPreferredSize(new java.awt.Dimension(82, 28));
        getContentPane().add(NewPassLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 107, -1, -1));

        UserIDField.setPreferredSize(new java.awt.Dimension(82, 28));
        getContentPane().add(UserIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 67, -1, -1));

        NewPassfField.setPreferredSize(new java.awt.Dimension(82, 28));
        getContentPane().add(NewPassfField, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 107, 140, -1));

        ResetButton.setText("Reset");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ResetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 167, -1, -1));

        LoginButton.setText("< Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 26, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseconnection/systembackground.png"))); // NOI18N
        background.setText("background");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        // TODO add your handling code here:
        String userID = UserIDField.getText().trim();
        String newPassword = NewPassfField.getText().trim();

        if (userID.isEmpty() || newPassword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in both fields.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try (Connection con = DatabaseConnection.getConnection();
             PreparedStatement pst = con.prepareStatement("UPDATE users SET password = ? WHERE userID = ?")) {

            pst.setString(1, newPassword);
            pst.setString(2, userID);

            int rowsUpdated = pst.executeUpdate();

            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(this, "Password successfully updated! Please log in.");
                new LoginInterface().setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "User ID not found.", "Reset Failed", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        new LoginInterface().setVisible(true);
        dispose();
    }//GEN-LAST:event_LoginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgetPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ForgetPassLabel;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel NewPassLabel;
    private javax.swing.JTextField NewPassfField;
    private javax.swing.JButton ResetButton;
    private javax.swing.JTextField UserIDField;
    private javax.swing.JLabel UserIDLabel;
    private javax.swing.JLabel background;
    // End of variables declaration//GEN-END:variables
}
