package databaseconnection;
import javax.swing.JOptionPane;

public class LoginInterface extends javax.swing.JFrame {

    public LoginInterface() {
        initComponents();
        setLocationRelativeTo(null); // Center the window
        LoginButton.addActionListener(evt -> handleLogin());
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginTitleLabel = new javax.swing.JLabel();
        UserIDLabel = new javax.swing.JLabel();
        UserIDField = new javax.swing.JTextField();
        PasswordLabel = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        UserTypeLabel = new javax.swing.JLabel();
        UserTypeComboBox = new javax.swing.JComboBox<>();
        LoginButton = new javax.swing.JButton();
        ForgetButton = new javax.swing.JButton();
        BackgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LoginTitleLabel.setText("LOGIN");
        getContentPane().add(LoginTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 34, -1, -1));

        UserIDLabel.setText("User ID:");
        getContentPane().add(UserIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 68, 82, 28));

        UserIDField.setMinimumSize(new java.awt.Dimension(82, 28));
        getContentPane().add(UserIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 147, 28));

        PasswordLabel.setText("Password:");
        PasswordLabel.setPreferredSize(new java.awt.Dimension(82, 28));
        getContentPane().add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        PasswordField.setPreferredSize(new java.awt.Dimension(82, 28));
        getContentPane().add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 147, -1));

        UserTypeLabel.setText("User Type:");
        UserTypeLabel.setPreferredSize(new java.awt.Dimension(82, 28));
        getContentPane().add(UserTypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 145, -1, -1));

        UserTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Staff" }));
        UserTypeComboBox.setPreferredSize(new java.awt.Dimension(82, 28));
        getContentPane().add(UserTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 147, -1));

        LoginButton.setText("Login");
        getContentPane().add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 191, -1, -1));

        ForgetButton.setText("Forget?");
        ForgetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForgetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ForgetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 191, -1, -1));

        BackgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseconnection/systembackground.png"))); // NOI18N
        BackgroundLabel.setText("Background");
        getContentPane().add(BackgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ForgetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForgetButtonActionPerformed
        // TODO add your handling code here:
        new ForgetPassword().setVisible(true);
        dispose();
    }//GEN-LAST:event_ForgetButtonActionPerformed

    private void handleLogin() {
        String userID = UserIDField.getText();
        String password = new String(PasswordField.getPassword());
        String userType = UserTypeComboBox.getSelectedItem().toString();

         try {
            User user = UserDAO.getUserByID(userID);
            if (user != null) {
                if (!user.getUserType().equalsIgnoreCase(userType)) {
                    throw new Exception("Incorrect user type for this user ID.");
                }
                if (!user.getPassword().equals(password)) {
                    throw new Exception("Incorrect password.");
                }

                // Login successful
                Session.userType = user.getUserType();
                Session.userName = user.getName();
                JOptionPane.showMessageDialog(this, "Login successful!");

                if (userType.equalsIgnoreCase("Admin")) {
                    new AdminPage().setVisible(true);
                } else {
                    new InventoryMangement().setVisible(true);
                }
                this.dispose();
            } else {
                throw new Exception("User not found.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Login Failed", JOptionPane.ERROR_MESSAGE);
            // Return to login
            new LoginInterface().setVisible(true);
            this.dispose();
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundLabel;
    private javax.swing.JButton ForgetButton;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel LoginTitleLabel;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JTextField UserIDField;
    private javax.swing.JLabel UserIDLabel;
    private javax.swing.JComboBox<String> UserTypeComboBox;
    private javax.swing.JLabel UserTypeLabel;
    // End of variables declaration//GEN-END:variables
}
