package databaseconnection;
import javax.swing.JOptionPane;
public class ModifyUser extends javax.swing.JFrame {

    public ModifyUser() {
        initComponents();
        setLocationRelativeTo(null); // Center the window
        SearchButton.addActionListener(evt -> handleSearchUser());
        UpdateButton.addActionListener(evt -> handleUpdateUser()); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ModifyUserLabel = new javax.swing.JLabel();
        UserManagementButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        UserIDLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        PNLabel = new javax.swing.JLabel();
        UserTypeLabel = new javax.swing.JLabel();
        UserIDField = new javax.swing.JTextField();
        NameField = new javax.swing.JTextField();
        EmailField = new javax.swing.JTextField();
        PhoneField = new javax.swing.JTextField();
        UserTypeComboBox = new javax.swing.JComboBox<>();
        UpdateButton = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();
        BackgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ModifyUserLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ModifyUserLabel.setText("MODIFY USER");
        getContentPane().add(ModifyUserLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 22, -1, -1));

        UserManagementButton.setText("< User Management");
        UserManagementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserManagementButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UserManagementButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 22, -1, -1));

        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 22, -1, -1));

        UserIDLabel.setText("User ID            :");
        UserIDLabel.setPreferredSize(new java.awt.Dimension(82, 28));
        getContentPane().add(UserIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 63, -1, -1));

        NameLabel.setText("Name              :");
        NameLabel.setPreferredSize(new java.awt.Dimension(82, 28));
        getContentPane().add(NameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 97, -1, -1));

        EmailLabel.setText("Email               :");
        EmailLabel.setPreferredSize(new java.awt.Dimension(82, 28));
        getContentPane().add(EmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 131, -1, -1));

        PNLabel.setText("Phone Number         :");
        PNLabel.setPreferredSize(new java.awt.Dimension(100, 28));
        getContentPane().add(PNLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 120, -1));

        UserTypeLabel.setText("User Type         :");
        UserTypeLabel.setPreferredSize(new java.awt.Dimension(82, 28));
        getContentPane().add(UserTypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 86, -1));

        UserIDField.setPreferredSize(new java.awt.Dimension(82, 28));
        UserIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserIDFieldActionPerformed(evt);
            }
        });
        getContentPane().add(UserIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 63, -1, -1));

        NameField.setPreferredSize(new java.awt.Dimension(82, 28));
        NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(NameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 97, -1, -1));

        EmailField.setPreferredSize(new java.awt.Dimension(150, 28));
        EmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailFieldActionPerformed(evt);
            }
        });
        getContentPane().add(EmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        PhoneField.setPreferredSize(new java.awt.Dimension(100, 28));
        getContentPane().add(PhoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        UserTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Staff" }));
        UserTypeComboBox.setPreferredSize(new java.awt.Dimension(100, 28));
        getContentPane().add(UserTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        UpdateButton.setText("Update");
        UpdateButton.setPreferredSize(new java.awt.Dimension(82, 28));
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 66, -1, -1));

        BackgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseconnection/systembackground.png"))); // NOI18N
        BackgroundLabel.setText("Background");
        BackgroundLabel.setMaximumSize(new java.awt.Dimension(800, 300));
        BackgroundLabel.setMinimumSize(new java.awt.Dimension(800, 300));
        BackgroundLabel.setPreferredSize(new java.awt.Dimension(800, 300));
        getContentPane().add(BackgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        // TODO add your handling code here:
        new LoginInterface().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void UserManagementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserManagementButtonActionPerformed
        // TODO add your handling code here:
        new UserManagement().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_UserManagementButtonActionPerformed

    private void UserIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserIDFieldActionPerformed

    private void EmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailFieldActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameFieldActionPerformed

    private void handleSearchUser() {
        String userID = UserIDField.getText().trim();

        if (userID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a User ID.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        User user = UserDAO.getUserByID(userID);
        if (user != null) {
            NameField.setText(user.getName());
            EmailField.setText(user.getEmail());
            PhoneField.setText(String.valueOf(user.getPhoneNum()));
            UserTypeComboBox.setSelectedItem(user.getUserType());
            JOptionPane.showMessageDialog(this, "User found. Fields populated.");
        } else {
            JOptionPane.showMessageDialog(this, "User ID not found.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void handleUpdateUser() {
        String userID = UserIDField.getText().trim();
        String name = NameField.getText().trim();
        String email = EmailField.getText().trim();
        String phoneStr = PhoneField.getText().trim();
        String userType = UserTypeComboBox.getSelectedItem().toString();

        if (userID.isEmpty() || name.isEmpty() || email.isEmpty() || phoneStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields must be filled.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            String phoneNum = phoneStr;
            UserDAO.updateUser(userID, name, email, phoneNum, userType);
            JOptionPane.showMessageDialog(this, "User updated successfully.");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid phone number.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundLabel;
    private javax.swing.JTextField EmailField;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JLabel ModifyUserLabel;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel PNLabel;
    private javax.swing.JTextField PhoneField;
    private javax.swing.JButton SearchButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JTextField UserIDField;
    private javax.swing.JLabel UserIDLabel;
    private javax.swing.JButton UserManagementButton;
    private javax.swing.JComboBox<String> UserTypeComboBox;
    private javax.swing.JLabel UserTypeLabel;
    // End of variables declaration//GEN-END:variables
}
