package databaseconnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
public class ViewSuppliers extends javax.swing.JFrame {

    public ViewSuppliers() {
        initComponents();
        setLocationRelativeTo(null); // Center the window
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ViewSupplierLabel = new javax.swing.JLabel();
        LogoutButton = new javax.swing.JButton();
        SupplierNameLabel = new javax.swing.JLabel();
        ContactPersonLabel = new javax.swing.JLabel();
        PhoneNumLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        AddressLabel = new javax.swing.JLabel();
        SearchButton = new javax.swing.JButton();
        SupplierNameField = new javax.swing.JTextField();
        BackgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ViewSupplierLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ViewSupplierLabel.setText("View Supplier");
        getContentPane().add(ViewSupplierLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 22, -1, -1));

        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 22, -1, -1));

        SupplierNameLabel.setText("Supplier Name:");
        SupplierNameLabel.setPreferredSize(new java.awt.Dimension(82, 28));
        getContentPane().add(SupplierNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 78, -1, -1));

        ContactPersonLabel.setText("Contact Person:");
        ContactPersonLabel.setPreferredSize(new java.awt.Dimension(300, 28));
        getContentPane().add(ContactPersonLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 112, -1, -1));

        PhoneNumLabel.setText("Phone Num     :");
        PhoneNumLabel.setPreferredSize(new java.awt.Dimension(300, 28));
        getContentPane().add(PhoneNumLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 146, -1, -1));

        EmailLabel.setText("Email                :");
        EmailLabel.setPreferredSize(new java.awt.Dimension(300, 28));
        getContentPane().add(EmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 180, -1, -1));

        AddressLabel.setText("Address           :");
        AddressLabel.setPreferredSize(new java.awt.Dimension(400, 28));
        getContentPane().add(AddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 220, -1, -1));

        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 81, -1, -1));

        SupplierNameField.setPreferredSize(new java.awt.Dimension(82, 28));
        getContentPane().add(SupplierNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 78, 127, -1));

        BackgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseconnection/systembackground.png"))); // NOI18N
        BackgroundLabel.setText("Background");
        getContentPane().add(BackgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        // TODO add your handling code here:
        new LoginInterface().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code her e:
        String supplierName = SupplierNameField.getText().trim();

    if (supplierName.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter supplier name.");
        return;
    }

    try (Connection conn = DatabaseConnection.getConnection();
         PreparedStatement stmt = conn.prepareStatement("SELECT * FROM supplier WHERE supplierName = ?")) {

        stmt.setString(1, supplierName);
        ResultSet rs = stmt.executeQuery();

        if (rs.next()) {
            SupplierNameLabel.setText("Supplier Name     : " + rs.getString("supplierName"));
            ContactPersonLabel.setText("Contact Person    : " + rs.getString("contactPerson"));
            PhoneNumLabel.setText("Phone Number      : " + rs.getInt("phoneNum"));
            EmailLabel.setText("Email             : " + rs.getString("email"));
            AddressLabel.setText("Address           : " + rs.getString("address"));
        } else {
            JOptionPane.showMessageDialog(this, "Supplier not found.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_SearchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewSuppliers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JLabel BackgroundLabel;
    private javax.swing.JLabel ContactPersonLabel;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JLabel PhoneNumLabel;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField SupplierNameField;
    private javax.swing.JLabel SupplierNameLabel;
    private javax.swing.JLabel ViewSupplierLabel;
    // End of variables declaration//GEN-END:variables
}
